# Generated by Django 5.1.1 on 2024-09-09 18:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoList', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='slug',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='todo',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 9, 9, 18, 32, 38, 216475)),
        ),
        migrations.AlterField(
            model_name='todo',
            name='date_end',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 9, 9, 18, 32, 38, 216475)),
        ),
    ]
