# Generated by Django 5.1.1 on 2024-09-09 20:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoList', '0003_alter_todo_date_alter_todo_date_end'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 9, 9, 20, 37, 33, 908295)),
        ),
        migrations.AlterField(
            model_name='todo',
            name='date_end',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 9, 9, 20, 37, 33, 908295)),
        ),
    ]
