# Generated by Django 5.1.1 on 2024-09-09 20:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoList', '0004_alter_todo_date_alter_todo_date_end'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='todo',
            name='date_end',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
